version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    expose:
      - 29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://kafka:29092

  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
    expose:
      - 6379

  init:
    build:
      dockerfile: ./packages/init/Dockerfile
    depends_on:
      - kafka
      - redis
    environment:
      KAFKA_HOST: kafka:29092
      REDIS_URL: redis://redis:6379
    restart: "no"

  crawler:
    build:
      dockerfile: ./packages/crawler/Dockerfile
    depends_on:
      - init
    environment:
      KAFKA_HOST: kafka:29092
    restart: always

  streaming:
    build:
      dockerfile: ./packages/streaming/Dockerfile
    depends_on:
      - init
    environment:
      KAFKA_HOST: kafka:29092
    restart: always

  persistence-adapter:
    build:
      dockerfile: ./packages/persistence-adapter/Dockerfile
    depends_on:
      - init
    environment:
      KAFKA_HOST: kafka:29092
      REDIS_URL: redis://redis:6379
    restart: always

  web:
    build:
      dockerfile: ./packages/web/Dockerfile
    depends_on:
      - init
    environment:
      REDIS_URL: redis://redis:6379
    restart: always
    ports:
      - 3000:3000
